"""Remove user_id from TradeEntry

Revision ID: 13f93be6f9fb
Revises: 313116050118
Create Date: 2026-09-10 12:33:03.794360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f93be6f9fb'
down_revision = '313116050118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_entry', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_trade_entry_entry_id', ['entry_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_entry', schema=None) as batch_op:
        batch_op.drop_constraint('uq_trade_entry_entry_id', type_='unique')

    # ### end Alembic commands ###
