"""Update model

Revision ID: 313116050118
Revises: ccb5b06d73f0
Create Date: 2026-09-10 09:28:24.505458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313116050118'
down_revision = 'ccb5b06d73f0'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('trade_entry', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
